### PR TITLE
Stage 2

### PR DESCRIPTION
**Pull request by GrantWasil**
Implemented Front-End design from Figma Markup

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Good job! Some corrections need to be made, but on the whole, the project is very impressive!

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
Some mismatches to the design:
* the "Search" button isn't displayed (except for mobile screens)
* favicon doesn't correspond to the design.
* Should be shown only on mobile screens: https://prnt.sc/x9gw28
* Incorrect card layout on /save-news, this is how it should be according to the design: https://prnt.sc/x9gzwa
* A horizontal scroll: https://prnt.sc/x9higw
- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
* These elements inside the navigation menu should be links with correctly specified href values: http://joxi.ru/bmoly4yUyvkZ92 and should open in new tabs
* No "preloader" and "nothing found" blocks. Please, add so that I can check the layout.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
Incorrect layout on tablet screens: https://prnt.sc/x9hbxr. The cards are too narrow.
The images on cards lose their proportions on intermediate resolutions: https://prnt.sc/x9hm0i https://prnt.sc/x9hoxy
- [ ]  There are no validation errors.
https://prnt.sc/x9gr0j
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
Would be better to use `<ul>` to mark up the cards collection.
Also, it's better to use a semantic tag `<header>` for the header and `<nav>` for the navigation menu in the header.
footer should be marked up as `<footer>`
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [ ]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.
Should be key-value modifiers: https://prnt.sc/x9ir6w
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
* Card bookmark on hover should have the following effect (when not logged in): http://joxi.ru/V2Vw0Z0CkJMy8A
* Card "remove" icon should have the following effect on hover: http://joxi.ru/eAOw8Q8CkjQ38A when logged in on "Saved Articles" page.
* not implemented: https://prnt.sc/x9iwas
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
- [ ]  The form must have placeholders, and required fields should be validated.
The required fields aren't validated, inputs don't have "required" attribute.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [ ]  System fonts are connected as alternatives to each of your fonts.
https://prnt.sc/x9j35v It's necessary to correct all similar cases
- [ ]  Raster and vector images have been optimized.

## Number of points: 35

**Comment by GrantWasil** [comment]
@ImaliaNsk 

Thank you for your fantastic feedback! I believe I have implemented the changes you are looking for. Let me know if there's anything else I can fix!

**Comment by GrantWasil** [comment]
@ImaliaNsk Just put through another few fixes I left out. Thanks again for your help.

**Comment by ImaliaNsk** [comment]
Thanks for the corrections sent, good job! However, some issues haven't been fixed, and some other appeared after the changes. Please, see below and correct.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
**Some mismatches to the design:**
**- the "Search" button isn't displayed: https://prnt.sc/xf19t2**
**- on tablet and desktop screens there should be three cards in a row, currently there are two: https://prnt.sc/xf1jhy. The same issue on "Home" page search results.**
**- Incorrect layout in footer on mobile screens: https://prnt.sc/xf2d6k**
**- The github and facebook icons aren't displayed on 511px and higher.**
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
**- Content isn't centered on some resolutions: https://prnt.sc/xf2avy**
**- The github and facebook icons aren't displayed on 511px and higher.**
- [ ]  There are no validation errors.
**https://prnt.sc/x9gr0j**
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [ ]  A components folder with JS and CSS files for the components.
	**https://prnt.sc/xf26l1**
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.
**Should be key-value modifiers: https://prnt.sc/xf2o4f, not boolean modifiers.**
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
**- Card bookmark on hover should have the following effect (when not logged in): http://joxi.ru/V2Vw0Z0CkJMy8A**
**- Card "remove" icon should have the following effect on hover: http://joxi.ru/eAOw8Q8CkjQ38A when logged in on "Saved Articles" page.**
**- not implemented: https://prnt.sc/x9iwas**
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [ ]  System fonts are connected as alternatives to each of your fonts.
**https://prnt.sc/xf2x9i It's necessary to correct all similar cases - the project contains a lot of similar issues, use search in your IDE**
- [ ]  Raster and vector images have been optimized.
**Raster images haven't been optimized**

## Number of points: 55

**Comment by GrantWasil** [comment]
Bam! @ImaliaNsk thanks again for your feedback. Submitting my new code now

**Comment by ImaliaNsk** [comment]
The project is getting better with every set of corrections! However, I still can't accept it because of some performance issues, I've commented them below in the list.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
**A horizontal scroll on 320-331, 511 - 525 https://prnt.sc/xgejy1 https://prnt.sc/xgexik**
**Sandwich menu isn't displayed on saved-news: https://prnt.sc/xgf778**
**Horizontal scroll and no close button: https://prnt.sc/xgfkdr**
**Please, let me know how to check the layout of the page "searching" with a Preloader, currently it looks incorrectly.**
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
**On mobile screens 3 cards in a row look incorrectly: https://prnt.sc/xgersn. Would be better to have one card there, or to make two cards for some resolutions about 540 - 750 and smaller **
- [ ]  There are no validation errors.
**https://prnt.sc/xggxi6**
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.
**This is just a different notation, but the modifiers are still boolean: https://prnt.sc/xggivk. It's necessary to change back to the "underscore" notation, but use key-value modifiers like `popup_type_register`**
**Besides, sorry for not indicating before, this should be a boolean modifier, not the element: https://prnt.sc/xggosr. The entity can't be a block and its own modifier at the same time, because an elements can't be used outside of its block, it should always be nested inside the block.**
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.
**Raster images haven't been optimized**

## Number of points: 64

**Comment by GrantWasil** [comment]
@ImaliaNsk Alright, we should be good this time! I have removed horizontal scroll from the whole app. Fixed BEM naming conventions, and I added the preloader to the main page so you can see it. Thank you so much for working with me on this.

**Comment by ImaliaNsk** [comment]
All good now, the project has been accepted, congratulations! Good luck on the next stage!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [x]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Raster and vector images have been optimized.
**Raster images haven't been optimized**

## Number of points: 97

**Pull request merged**
